apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zgzcdvmf0-go
  janus-idp.io/tekton: zgzcdvmf0-go
  backstage.io/kubernetes-id: zgzcdvmf0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zgzcdvmf0-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
